blank_issues_enabled: false

contact_links:

  - name: Cloud Innovation Platform Community Slack Team
    url: https://slack.sgcip.com/
    about: |-
      Please ask and answer questions here.

  - name: CloudPosse's Community Slack Team
    url: https://cloudposse.com/slack/
    about: |-
      Please ask and answer questions here.